~/bin/asciidoctor -D output -a rouge-style=base16 -a stylesheet=css/adoc.css -o nimprogramming_rouge_base16.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=bw -a stylesheet=css/adoc.css -o nimprogramming_rouge_bw.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=colorful -a stylesheet=css/adoc.css -o nimprogramming_rouge_colorful.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=github -a stylesheet=css/adoc.css -o nimprogramming_rouge_github.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=gruvbox -a stylesheet=css/adoc.css -o nimprogramming_rouge_gruvbox.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=igor_pro -a stylesheet=css/adoc.css -o nimprogramming_rouge_igor_pro.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=magritte -a stylesheet=css/adoc.css -o nimprogramming_rouge_magritte.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc.css -o nimprogramming_rouge_molokai.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=monokai -a stylesheet=css/adoc.css -o nimprogramming_rouge_monokai.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=monokai_sublime -a stylesheet=css/adoc.css -o nimprogramming_rouge_monokai_sublime.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=pastie -a stylesheet=css/adoc.css -o nimprogramming_rouge_pastie.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=thankful_eyes -a stylesheet=css/adoc.css -o nimprogramming_rouge_thankful_eyes.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=tulip -a stylesheet=css/adoc.css -o nimprogramming_rouge_tulip.html nimprogramming.adoc

~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc.css -a attribute-missing=warn -o nimprogramming.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-colony.css -o nimprogramming_adoc-colony.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-foundation.css -o nimprogramming_adoc-foundation.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-foundation-lime.css -o nimprogramming_adoc-foundation-lime.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-foundation-potion.css -o nimprogramming_adoc-foundation-potion.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-github.css -o nimprogramming_adoc-github.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-golo.css -o nimprogramming_adoc-golo.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-iconic.css -o nimprogramming_adoc-iconic.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-maker.css -o nimprogramming_adoc-maker.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=github -a stylesheet=css/adoc-readthedocs.css -o nimprogramming_adoc-readthedocs.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-riak.css -o nimprogramming_adoc-riak.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-rocket-panda.css -o nimprogramming_adoc-rocket-panda.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc-rubygems.css -o nimprogramming_adoc-rubygems.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/asciidoc-classic.css -o nimprogramming_asciidoc-classic.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/asciidoctor.css -o nimprogramming_asciidoctor.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-cerulean.css -o nimprogramming_boot-cerulean.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-cosmo.css -o nimprogramming_boot-cosmo.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-cyborg.css -o nimprogramming_boot-cyborg.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-darkly.css -o nimprogramming_boot-darkly.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-flatly.css -o nimprogramming_boot-flatly.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-journal.css -o nimprogramming_boot-journal.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-lumen.css -o nimprogramming_boot-lumen.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-paper.css -o nimprogramming_boot-paper.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-readable.css -o nimprogramming_boot-readable.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-sandstone.css -o nimprogramming_boot-sandstone.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-slate.css -o nimprogramming_boot-slate.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-spacelab.css -o nimprogramming_boot-spacelab.html nimprogramming.adoc
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-superhero.css -o nimprogramming_boot-superhero.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/boot-yeti.css -o nimprogramming_boot-yeti.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/clean.css -o nimprogramming_clean.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/dark.css -o nimprogramming_dark.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/fedora.css -o nimprogramming_fedora.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/gazette.css -o nimprogramming_gazette.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/italian-pop.css -o nimprogramming_italian-pop.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-amber.css -o nimprogramming_material-amber.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-blue.css -o nimprogramming_material-blue.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-brown.css -o nimprogramming_material-brown.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-green.css -o nimprogramming_material-green.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-grey.css -o nimprogramming_material-grey.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-orange.css -o nimprogramming_material-orange.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-pink.css -o nimprogramming_material-pink.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-purple.css -o nimprogramming_material-purple.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-red.css -o nimprogramming_material-red.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/material-teal.css -o nimprogramming_material-teal.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/medium.css -o nimprogramming_medium.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/monospace.css -o nimprogramming_monospace.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/notebook.css -o nimprogramming_notebook.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/plain.css -o nimprogramming_plain.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/template.css -o nimprogramming_template.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/tufte.css -o nimprogramming_tufte.html nimprogramming.adoc
#~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/ubuntu.css -o nimprogramming_ubuntu.html nimprogramming.adoc

cp nimprogramming.adoc nimprog.adoc
bash ./sedscriptforbackticks
~/bin/asciidoctor -D output -a rouge-style=molokai -a stylesheet=css/adoc.css -o nimprog.html nimprog.adoc
